import { ConvexClientProvider } from "@/components/providers/convex-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description:
    "Generated by create next app",
  icons: {
    icon: [
      {
        media:
          "(prefers-color-scheme: light)",
        url: "./default/logo.svg",
        href: "./default/logo.svg",
      },
      {
        media:
          "(prefers-color-scheme: dark)",
        url: "./dark/logo.svg",
        href: "./dark/logo.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={
          inter.className +
          " dark:bg-[#1F1F1F]"
        }
      >
        <ConvexClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            storageKey={"notion-clone"}
          >
            {children}
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
